const types = {

    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    SIGN_UP: 'SIGN_UP',

    FETCH_TIERS: 'FETCH_TIERS',
    FETCH_PLAYLISTS: 'FETCH_PLAYLIST',
    FETCH_PLAYLIST: 'FETCH_PLAYLIST',
    FETCH_BAND: 'FETCH_BAND',
    FETCH_BANDS: 'FETCH_BANDS',
    FETCH_TITLES: 'FETCH_TITLES',
    FETCH_VERSIONS: 'FETCH_VERSIONS',
    FETCH_BOUNCES: 'FETCH_BOUNCES',

    CREATE_TIER: 'CREATE_TIER',
    CREATE_PLAYLIST: 'CREATE_PLAYLIST',
    CREATE_PLAYLISTSONG: 'CREATE_PLAYLISTSONG',
    CREATE_TITLE: 'CREATE_TITLE',
    CREATE_VERSION: 'CREATE_VERSION',
    CREATE_BOUNCE: 'CREATE_BOUNCE',
    CREATE_BAND: 'CREATE_BAND',

    EDIT_TIER: 'EDIT_TIER',
    EDIT_PLAYLIST: 'EDIT_PLAYLIST',
    EDIT_PLAYLISTSONG: 'EDIT_PLAYLISTSONG',
    EDIT_TITLE: 'EDIT_TITLE',
    EDIT_VERSION: 'EDIT_VERSION',
    EDIT_BOUNCE: 'EDIT_BOUNCE',
    EDIT_BAND: 'EDIT_BAND',

    DELETE_TIER: 'DELETE_TIER',
    DELETE_PLAYLIST: 'DELETE_PLAYLIST',
    DELETE_PLAYLISTSONG: 'DELETE_PLAYLISTSONG',
    DELETE_TITLE: 'DELETE_TITLE',
    DELETE_VERSION: 'DELETE_VERSION',
    DELETE_BOUNCE: 'DELETE_BOUNCE',
    DELETE_BAND: 'DELETE_BAND',
};

export default types;