const types = {

    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    SIGN_UP: 'SIGN_UP',
    FETCH_ALL: 'FETCH_ALL',
    FETCH_MP3: 'FETCH_MP3',
    CREATE_TIER: 'CREATE_TIER',
    CREATE_TITLE: 'CREATE_TITLE',
    CREATE_VERSION: 'CREATE_VERSION',
    CREATE_BOUNCE: 'CREATE_BOUNCE',
    CREATE_BAND: 'CREATE_BAND',
    EDIT_TIER: 'EDIT_TIER',
    EDIT_TITLE: 'EDIT_TITLE',
    EDIT_VERSION: 'EDIT_VERSION',
    EDIT_BOUNCE: 'EDIT_BOUNCE',
    EDIT_BAND: 'EDIT_BAND',
    DELETE_TIER: 'DELETE_TIER',
    DELETE_TITLE: 'DELETE_TITLE',
    DELETE_VERSION: 'DELETE_VERSION',
    DELETE_BOUNCE: 'DELETE_BOUNCE',
    DELETE_BAND: 'DELETE_BAND',
};

export default types;